/** The zero-shot model that names objects, and how each kind is phrased for it. */
export const KIND_MODEL = "Xenova/mobileclip_s0";
export const KIND_TEMPLATE = "a photo of a {}";

/**
 * The kinds of everyday object the scanner can name (zero-shot, so the list is
 * just words). Singular, lowercase, as a person would say it. After changing
 * it, rebuild public/models/object-kinds.* (npm run kinds).
 */
export const OBJECT_KINDS = [
  // Pocket and desk
  "lighter",
  "pen",
  "pencil",
  "marker",
  "eraser",
  "stapler",
  "box",
  "scissors",
  "notebook",
  "book",
  "calculator",
  "wallet",
  "key",
  "keychain",
  "coin",
  "credit card",
  "comb",
  "lipstick",
  "perfume bottle",
  "sunglasses",
  "glasses",
  "watch",
  "ring",
  "bracelet",
  "necklace",
  "earring",
  // Tech
  "phone",
  "tablet",
  "laptop",
  "computer keyboard",
  "computer mouse",
  "headphones",
  "earbuds case",
  "remote control",
  "game controller",
  "camera",
  "speaker",
  "charger",
  "power bank",
  "usb stick",
  "smartwatch",
  // Kitchen and table
  "mug",
  "cup",
  "glass",
  "bottle",
  "water bottle",
  "wine bottle",
  "can",
  "jar",
  "plate",
  "bowl",
  "spoon",
  "fork",
  "knife",
  "teapot",
  "kettle",
  "frying pan",
  "cutting board",
  "salt shaker",
  // Food
  "banana",
  "apple",
  "orange",
  "lemon",
  "pear",
  "strawberry",
  "tomato",
  "avocado",
  "egg",
  "bread",
  "cookie",
  "chocolate bar",
  // Home
  "candle",
  "vase",
  "lamp",
  "plant pot",
  "picture frame",
  "clock",
  "alarm clock",
  "pillow",
  "towel",
  "toothbrush",
  "soap",
  "hairbrush",
  "umbrella",
  "flashlight",
  "battery",
  "light bulb",
  "tape",
  "screwdriver",
  "hammer",
  "wrench",
  // Toys and hobby
  "teddy bear",
  "doll",
  "figurine",
  "toy car",
  "rubber duck",
  "ball",
  "tennis ball",
  "basketball",
  "football",
  "dice",
  "playing card",
  "puzzle piece",
  "guitar",
  "skateboard",
  "yo-yo",
  // Wearables
  "sneaker",
  "shoe",
  "cap",
  "hat",
  "sock",
  "glove",
  "backpack",
  "handbag",
  "belt",
  "scarf",
  "t-shirt",
];
